### ISSUE TITLE
Windows 8 - open the terminal instruction

### ISSUE THREAD

**Issue by rotev** [railsgirls/railsgirls.github.io#134]
step 1 "open a terminal".
On Windows 8 , there is no "Start", so in order to open a terminal
you can do one of the following (there are more options too):
1. Win + R , type 'cmd'
1. Win + X, select 'command prompt'
1. in app view, in search tab, type 'cmd'

**Comment by brownbonnie** [comment]
I've completed this change but when I push it I get the following error message:

ERROR: Permission to railsgirls/railsgirls.github.io.git denied to brownbonnie.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Can anyone help with this?

**Comment by brownbonnie** [comment]
I've made this change on a fork 

https://github.com/brownbonnie/railsgirls.github.io

**Comment by Tess007** [comment]
I want to work on this issue
Thank you
