### ISSUE TITLE
Introduction to Ruby Concepts?

### ISSUE THREAD

**Issue by ghost** [railsgirls/railsgirls.github.io#289]
Hi, 

I was wondering if someone has suggested adding some explanations of Ruby in the Rails tutorial? For complete beginners it is quite difficult to understand and in the end I felt like I was simply following instructions and not actually knowing what I was doing. 
Have you had much feedback about this?

Thanks for all your efforts into making the tutorial. 

-Meagan

**Comment by vesan** [comment]
The guide has been written to be used with the coach. So if you follow it without one, you will miss out on the explanations of the coaches and won't have a chance to ask questions.

Regardless having a separate basics of Ruby guide would make sense to me.

**Comment by alicetragedy** [comment]
+1 on having a separate "basics of Ruby" guide, I like the idea. I agree that a lot of the basics will/should be explained by the coach, and that in most workshops the attendees will also be using tools like tryruby.org, which (try to) explain the Ruby syntax.
