### ISSUE TITLE
Questions about Guides

### ISSUE THREAD

**Issue by ChidoriY** [railsgirls/railsgirls.github.io#299]
Nice to meet you, I am a newbie from Railsgirls Japan. 
I started Ruby on Rails (nice) on Railsgirls Tokyo in this summer, and now I am studying by <a href="http://guides.railsgirls.com/">Rails Girls Guides</a>. And personally I think I would like to study "Design your table" on "<a href="http://guides.railsgirls.com/design-html-css">10 Design your App with HTML and CSS</a>" before <a href="http://guides.railsgirls.com/design">6 Apply a modern design with Bootstrap</a> because we have already replaced the table layout with a div layout on Lesson 6. 
And "Design the idea details page" on Lesson 6 does not seem it cares about "Render the comment form and existing comments" on <a href="http://guides.railsgirls.com/commenting">5 Allow Comments on Your App</a>.

Would you please help me? Thanks,

**Comment by Tsilly** [comment]
@ChidoriY. What can i do for you?

**Comment by ChidoriY** [comment]
Thanks for helping me!
Excuse me, but why isn't the code on <a href="http://guides.railsgirls.com/design">Design the idea details page</a> like this? :
<pre>
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-md-9">
    <%= image_tag(@idea.picture_url, width: '100%') if @idea.picture.present? %>
    <h3>Comments</h3>
    <% @comments.each do |comment| %>
    <div>
      <strong><%= comment.user_name %></strong>
      <br />
      <p><%= comment.body %></p>
      <p><%= link_to 'Delete', comment_path(comment), method: :delete, data: { confirm: 'Are you sure?' } %></p>
    </div>
    <% end %>
    <%= render 'comments/form' %>
  </div>
  
  <div class="col-md-3">
    <p><b>Name: </b><%= @idea.name %></p>
    <p><b>Description: </b><%= @idea.description %></p>
    <p>
      <%= link_to 'Edit', edit_idea_path(@idea) %> |
      <%= link_to 'Destroy', @idea, data: { confirm: 'Are you sure?' }, method: :delete %> |
      <%= link_to 'Back', ideas_path %>
    </p>
  </div>
</div>
</pre>

**Comment by Tsilly** [comment]
@ChidoriY. It doesn't seem to be an issue. Maybe you need a coach to discuss about the design.

**Comment by emorima** [comment]
@Tsilly Thanks your help.
I'm a coach of Rails Girls Tokyo and I can help @ChidoriY on Rails Girls Tokyo slack.  😄 

@ChidoriY Hi, Irie-san.  Let's talk about your question in Rails Girls Tokyo More's slack! 😉

**Comment by ChidoriY** [comment]
@Tsilly
Umm... I only hope these guides will have codes which help beginners who study rails by this guide <b>in order of lessons</b>.

@emorima
Thank you for helping in more@Slack!
