### ISSUE TITLE
Mac OS X 10.6 RailsInstaller too outdated for Rails 5.x.x

### ISSUE THREAD

**Issue by fabmann** [railsgirls/railsgirls.github.io#320]
While following the installation guide ( http://guides.railsgirls.com/install#setup-for-os-x ) for Mac OS 10.6 a participant discovered today that the command
`gem update rails`
fails, because a ruby version >= 2.2.2 is needed to update to rails 5.

**Comment by mpapis** [comment]
OSX 10.6 Railsinstaller will not be getting updates (not sure if it will be getting updates at all as I was preparing it in the past and I got no time for that anymore).

You could try:

```bash
gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
\curl -sSL https://get.rvm.io | bash -s stable --rails
```

[RVM](http://rvm.io) is still being supported and in case of any problems you should get help.

**Comment by hsbt** [comment]
This report is outdated today. We can install Ruby at macOS via https://guides.railsgirls.com/install/macos
