### ISSUE TITLE
Update RSpec testing for idea 

### ISSUE THREAD

**Issue by anaschwendler** [railsgirls/railsgirls.github.io#347]
Can I update the RSpec testing for the idea app?
Today I did the full tutorial again and saw that that the this part of the tutorial is out of date:
https://github.com/railsgirls/railsgirls.github.io/blob/master/_posts/2014-01-30-testing.markdown

Can I update and open an pull request for it?

**Comment by vesan** [comment]
@anaschwendler Please do!
