### ISSUE TITLE
Possible errors is often executes regardless of any problems

### ISSUE THREAD

**Issue by AndreasHassing** [railsgirls/railsgirls.github.io#378]
Hi RailsGirls community,

I coached a install session yesterday and found a lot of the Windows users to continue with the steps found in the troubleshooting guide (Possible errors).

Have any of you experienced this as well? If so, it would be beneficial to attempt to fix it.

The way I see it, there are a couple of ways to go about it:
1. Move the troubleshooting guide away from after step #1, to the bottom of the Windows guide perhaps, and instead provide a hashbang link to it.
2. Collapse the troubleshooting guide, and let attendees open it on-demand if needed. Does the static page renderer have such a collapse/spoiler construct?
3. Explicitly declare that: "hey, you are entering the troubleshooting guide, if you don't have any issues at this point skip to section #2 ((with a link to let them jump to it))".

What are your thoughts?

/Andreas

**Comment by tombruijn** [comment]
Hi @AndreasHassing,

Thanks for the feedback!
I noticed some of the same problems as well and addressed them in #442.
Let me know if you have any feedback on it :)
