### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by alfielytorres** [railsgirls/railsgirls.github.io#387]
Gem files will remain installed in
/Users/AlfieLuigi/railsgirls.github.io/vendor/bundle/ruby/2.5.0/gems/commonmarker-0.17.11
for inspection.
Results logged to
/Users/AlfieLuigi/railsgirls.github.io/vendor/bundle/ruby/2.5.0/extensions/x86_64-darwin-16/2.5.0/commonmarker-0.17.11/gem_make.out

An error occurred while installing commonmarker (0.17.11), and Bundler
cannot continue.
Make sure that `gem install commonmarker -v '0.17.11'` succeeds before
bundling.

In Gemfile:
  github-pages was resolved to 191, which depends on
    jekyll-commonmark-ghpages was resolved to 0.1.5, which depends on
      jekyll-commonmark was resolved to 1.2.0, which depends on
        commonmarker

**Comment by alfonsolytorres** [comment]
192-168-1-2:railsgirls.github.io AlfieLuigi$ gem install bundler
Successfully installed bundler-1.16.6
Parsing documentation for bundler-1.16.6
^[[A^[[ADone installing documentation for bundler after 2 seconds
1 gem installed
192-168-1-2:railsgirls.github.io AlfieLuigi$ bundle install --path vendor/bundle
Fetching gem metadata from https://rubygems.org/.........
Using concurrent-ruby 1.0.5
Using i18n 0.9.5
Using minitest 5.11.3
Using thread_safe 0.3.6
Using tzinfo 1.2.5
Using activesupport 4.2.10
Using public_suffix 2.0.5
Using addressable 2.5.2
Using bundler 1.16.6
Using coffee-script-source 1.11.1
Using execjs 2.7.0
Using coffee-script 2.4.1
Using colorator 1.1.0
Using ruby-enum 0.7.2
Fetching commonmarker 0.17.11
Installing commonmarker 0.17.11 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
/Users/AlfieLuigi/railsgirls.github.io/vendor/bundle/ruby/2.5.0/gems/commonmarker-0.17.11/ext/commonmarker
/usr/local/opt/ruby/bin/ruby -r ./siteconf20181023-5922-9hqb13.rb extconf.rb
creating Makefile

current directory:
/Users/AlfieLuigi/railsgirls.github.io/vendor/bundle/ruby/2.5.0/gems/commonmarker-0.17.11/ext/commonmarker
make "DESTDIR=" clean
xcrun: error: invalid active developer path
(/Library/Developer/CommandLineTools), missing xcrun at:
/Library/Developer/CommandLineTools/usr/bin/xcrun

current directory:
/Users/AlfieLuigi/railsgirls.github.io/vendor/bundle/ruby/2.5.0/gems/commonmarker-0.17.11/ext/commonmarker
make "DESTDIR="
xcrun: error: invalid active developer path
(/Library/Developer/CommandLineTools), missing xcrun at:
/Library/Developer/CommandLineTools/usr/bin/xcrun

make failed, exit code 1

Gem files will remain installed in
/Users/AlfieLuigi/railsgirls.github.io/vendor/bundle/ruby/2.5.0/gems/commonmarker-0.17.11
for inspection.
Results logged to
/Users/AlfieLuigi/railsgirls.github.io/vendor/bundle/ruby/2.5.0/extensions/x86_64-darwin-16/2.5.0/commonmarker-0.17.11/gem_make.out

An error occurred while installing commonmarker (0.17.11), and Bundler
cannot continue.
Make sure that `gem install commonmarker -v '0.17.11' --source
'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  github-pages was resolved to 191, which depends on
    jekyll-commonmark-ghpages was resolved to 0.1.5, which depends on
      jekyll-commonmark was resolved to 1.2.0, which depends on
        commonmarker
192-168-1-2:railsgirls.github.io AlfieLuigi$

**Comment by cappert** [comment]
Seems like you're missing the Xcode Command Line Tools (`xcrun missing...`).

`xcode-select --install` should fix it.

otherwise look at [this thread on stackoverflow](https://apple.stackexchange.com/questions/321858/xcrun-missing-installing-xcode-command-line-tools-not-fixing-issue).
