### ISSUE TITLE
Some links in Rail Girls guides are broken

### ISSUE THREAD

**Issue by shayanealcantara** [railsgirls/railsgirls.github.io#398]
#### Description:
I was searching ways to know better the organization and unfortunately, some links in those topics were broken. So I think that it's time to make a doc update, because the project is so cool, and then people could enjoy better :) 

An example in yellow: 

![image](https://user-images.githubusercontent.com/33501171/49688634-49b37380-fafc-11e8-9ece-f6a9e3518c81.png)

#### Steps to get the behavior:
- Enter in Rail Girls Guide `http://guides.railsgirls.com/`;
- Click on `How to organize a Rail Girls Event`;
- Try to access links in the page, like: `'organizer's Slack discussions forum`.

#### Expected behavior: 
When someone clicks in a link, access its content.

**Comment by vesan** [comment]
The link works now.

Thanks for opening an issue about it!
