### ISSUE TITLE
Update Ruby & Rails versions where needed in the install guide

### ISSUE THREAD

**Issue by morinoko** [railsgirls/railsgirls.github.io#430]
Let's update the Ruby version to 2.6.5 and Rails version to 6.0.0 in the install guide!
* EDIT: Ruby should now be 2.7.0

- [x] *Build Ruby with rbenv* lists ruby 2.6.3
- [x] Rbenv *Set default Ruby* lists ruby 2.6.3.
- [x] *Setup for Windows* still lists rails 5.1.1

**Comment by igaiga** [comment]
On Windows, Japanese guide has a descriptions of Rails 6.0 and Ruby2.6 using WSL and RubyInstaller. And we're using the (Japanese) guide in our rails girls events. They looks working well.

http://railsgirls.jp/install#setup_for_windows

So, on Windows, I think it's good to translate from Japanese to English. And Japanese Rails girls team members are translating the contents. (We need time...)

**Comment by morinoko** [comment]
Just made a pull request that updates the ruby version to 2.7.0.

Still need to do the Windows section.

**Comment by tombruijn** [comment]
I've updated the windows rails version in #442. Closing this issue 😄 

Any WSL work can be picked up under #394
