### ISSUE TITLE
Devise guide - Add sign-up and login links: remove `protect_from_forgery` comment

### ISSUE THREAD

**Issue by morinoko** [railsgirls/railsgirls.github.io#431]
Devise guide tells students to

> Open up `app/controllers/application_controller.rb` and add:
>   `before_action :authenticate_user!`
> after `protect_from_forgery with: :exception`.

But `protect_from_forgery with: :exception` is not longer present in Rails 6, so this comment can be removed.

**Comment by vesan** [comment]
@morinoko You want to create a pull request of this change?

**Comment by morinoko** [comment]
@vesan Sorry it took so long, but I finally created a pull request: https://github.com/railsgirls/railsgirls.github.io/pull/439

**Comment by vesan** [comment]
Thanks! Merged the PR.
