### ISSUE TITLE
Hover color of links on navbar is bad for reading

### ISSUE THREAD

**Issue by RafaelaMachado** [railsgirls/railsgirls.github.io#455]
![Captura de tela de 2021-04-12 23-43-56](https://user-images.githubusercontent.com/11599474/114489484-94bc8480-9be9-11eb-8db8-7fada3e3bd5a.png)

**Comment by Dharmi26** [comment]
**Can I be given a chance to fix this issue ?**

**Comment by Dharmi26** [comment]
**Can I be given a chance to fix this issue ?**

**Comment by RafaelaMachado** [comment]
Hello @Dharmi26 , this ISSUE I opened and already sent a PR with the solution. Sorry.

Feel free to evaluate [PR](https://github.com/railsgirls/railsgirls.github.io/pull/456)

**Comment by Dharmi26** [comment]
No worries...😊😌
