### ISSUE TITLE
Link in sidebar is to http and doesn't redirect to https

### ISSUE THREAD

**Issue by weex** [railsgirls/railsgirls.github.io#460]
To reproduce click on the link in the sidebar of this repo. You'll get a not secure warning.

**Comment by manoj1749** [comment]
could you assign me this, I like to work on it

**Comment by mmu094** [comment]
Yes sure plz go ahead one more issue it's swith PayPal

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by manoj1749** [comment]
there are 2 ways of doing this.
making a slight change in the repo and making a slight change in the settings of the repo, I will make the changes in the repo and put up a pr, after it's merged I can guide who had access to the settings to solve the issue.
If it's ok I will make the changes and put a pr.

**Comment by mmu094** [comment]
I can give you access for that

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by manoj1749** [comment]
ok then letme make the pr and update you

**Comment by mmu094** [comment]
THANKS MATE!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by manoj1749** [comment]
Made required changes and made a pr #473

**Comment by manoj1749** [comment]
after merging it we can made the other required changes in the settings of the repo

**Comment by manoj1749** [comment]
@mmu094

**Comment by manoj1749** [comment]
If you go to the settings of the repository, there will be pages option in the sidebar. When u click on it, it'll be showing you a option called "Enforce HTTPS", select it and update the current link in sidebar. Then this issue will be solved and then you can close this issue.😁

**Comment by mmu094** [comment]
Any update on rizqshops.com

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by manoj1749** [comment]
could you specify it

**Comment by mmu094** [comment]
Guys take a look at attached note that it's my account in PayPal freeze since months and I'm unable to perform any transactions

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by manoj1749** [comment]
There is nothing attached to the message u had sent

**Comment by hsbt** [comment]
@mmu094 is SPAM account. Do not respond for them.
