### ISSUE TITLE
Google Group Unavailable

### ISSUE THREAD

**Issue by Reiningecho90** [railsgirls/railsgirls.github.io#461]
I recently found this repo and wanted to join the google groups link for the mailing list in the README. When trying to join the Google Group I am met with this image:

![Screenshot 2022-02-05 095446](https://user-images.githubusercontent.com/68622369/152646949-7b778af2-8bec-4050-80f9-561a49fcc02d.png)

Is there anything I can do to get this to work on my side? 

Thanks for your help!

**Comment by JamesJames12321** [comment]
已收到，谢谢您的来信

**Comment by vesan** [comment]
Thanks for letting us know.

If you try again now, it should show you a link to apply for membership.

**Comment by JamesJames12321** [comment]
已收到，谢谢您的来信

**Comment by Reiningecho90** [comment]
Thank you! It works now!
