### ISSUE TITLE
HTML tags are not used properly 

### ISSUE THREAD

**Issue by nishi6verma** [railsgirls/railsgirls.github.io#468]
HTML tags are not used properly. Coding is not done in a proper way. Meta data is missing.

**Comment by vesan** [comment]
@nishi6verma do you want to open a pull request to fix the issues?

**Comment by nishi6verma** [comment]
Yes, I want to open a pull request. Pl. give me permission.

**Comment by mmu094** [comment]
Hello guys

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by vesan** [comment]
@nishi6verma You don't need permission. The repository is open for PRs.

**Comment by mmu094** [comment]
😊

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
