### ISSUE TITLE
Need to update Link in sidebar

### ISSUE THREAD

**Issue by manoj1749** [railsgirls/railsgirls.github.io#477]
issue #460  is not solved

- someone who has access to edit the about section need to change the website link to this--> https://guides.railsgirls.com

<img width="1440" alt="Screenshot 2022-10-10 at 10 32 50 PM" src="https://user-images.githubusercontent.com/83648898/194918710-ae26459b-bff5-4f76-b800-0355de7760f9.png">

- then only this issue can be resolved

**Comment by hsbt** [comment]
done

**Comment by mmu094** [comment]
Need your support to get it back online 

http://www.rizqshops.com/?fbclid=IwAR0NqC2cYYBGp2dL0mqA3Y8HOqctD-nr7tFl91ilNtmX_J3LaEFfYY_hTvQ
