### ISSUE TITLE
Ruby Sass has reached end-of-life and should no longer be used.

### ISSUE THREAD

**Issue by sbol-coolblue** [railsgirls/railsgirls.github.io#497]
Upon running `bundle install`, a post-install message is emitted:

> Ruby Sass has reached end-of-life and should no longer be used.
> * If you use Sass as a command-line tool, we recommend using Dart Sass, the new
>  primary implementation: https://sass-lang.com/install
> * If you use Sass as a plug-in for a Ruby web framework, we recommend using the
>  sassc gem: https://github.com/sass/sassc-ruby#readme
> * For more details, please refer to the Sass blog:
>   https://sass-lang.com/blog/posts/7828841

**Comment by tombruijn** [comment]
Hey @sbol-coolblue, Thanks for the report!

This site doesn't use Sass, but it's part of the GitHub pages gem bundle by default. This warning can be ignored. There is an issue open for this upstream. Hopefully it will be resolved soon.

- https://github.com/github/pages-gem/issues/813

Alternatively, we could use the Jekyll gem directly, with the github-pages gem. That will require a lot less gems and works roughly the same.

**Comment by tombruijn** [comment]
This is fixed by using the Jekyll gem directly, without the github-pages gem, in commit ecccaeb2b0beee6eb7727e4dd67c1219e13db6e0.
